function [fitresult, gof] = fitPlane(X, Y, minMap)
%CREATEFIT1(X,Y,MINMAP)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : X
%      Y Input : Y
%      Z Output: minMap
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 07-Aug-2018 09:48:40


%% Fit: 'untitled fit 1'.
[xData, yData, zData] = prepareSurfaceData( X, Y, minMap );

% Set up fittype and options.
ft = fittype( 'a + b*x + c*y', 'independent', {'x', 'y'}, 'dependent', 'z' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.496237484516514 0.606054931874717 0.0854079866336421];

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft, opts );


