function handles = centerTexts(handles)
centerText(handles.uicontrols.text.text_currentTask);
% centerText(handles.uicontrols.text.text_imageDetails_scaling_dxy);
% centerText(handles.uicontrols.text.text_imageDetails_scaling_dxyUnit);
% centerText(handles.uicontrols.text.text_imageDetails_scaling_dz);
% centerText(handles.uicontrols.text.text_imageDetails_scaling_dzUnit);
% centerText(handles.uicontrols.text.text_visCell_bins);
% centerText(handles.uicontrols.text.text_visCell_range);
% centerText(handles.uicontrols.text.text_workflow_imagePreparation_deconvolution_obj);
% centerText(handles.uicontrols.text.text_workflow_imagePreparation_deconvolution_alg);
% centerText(handles.uicontrols.text.text_workflow_imagePreparation_deconvolution_it);
% centerText(handles.uicontrols.text.text_workflow_imagePreparation_deconvolution_qual);
% centerText(handles.uicontrols.text.text_workflow_imagePreparation_deconvolution_snr);
% centerText(handles.uicontrols.text.text_workflow_simulationInput_lengthScale);
% centerText(handles.uicontrols.text.text_workflow_simulationInput_samplingUnit);
% centerText(handles.uicontrols.text.text_workflow_simulationInput_sampling);
% centerText(handles.uicontrols.text.text_workflow_simulationInput_samplingUnit);
% centerText(handles.uicontrols.text.text_workflow_simulationInput_timescale);
% centerText(handles.uicontrols.text.text_workflow_simulationInput_timescaleUnit);
% centerText(handles.uicontrols.text.text_workflow_simulationInput_cellExpansionFactor);
% centerText(handles.uicontrols.text.text_segmentationControl_methodDescr);
% centerText(handles.uicontrols.text.text_segmentationControl_ch);
% centerText(handles.uicontrols.text.text_workflow_segmentation_imageSettings_refCropUnit);
% centerText(handles.uicontrols.text.text_workflow_segmentation_imageSettings_cropUnit);
% centerText(handles.uicontrols.text.text_workflow_segmentation_imageSettings_zCrop_maxHeight);
% centerText(handles.uicontrols.text.text_workflow_segmentation_imageSettings_zCrop_maxHeightUnit);
% centerText(handles.uicontrols.text.text_workflow_segmentation_imageSettings_flowUnit);
% centerText(handles.uicontrols.text.text_workflow_segmentation_preprocessing_scaleUnit);
% centerText(handles.uicontrols.text.text_workflow_segmentation_denoising_tophatUnit);
% centerText(handles.uicontrols.text.text_workflow_segmentation_edgeDetection_fadeUnit);
% centerText(handles.uicontrols.text.text_workflow_segmentation_edgeDetection_kernelSizeDescr);
% centerText(handles.uicontrols.text.text_workflow_segmentation_edgeDetection_kernelSizeUnit);
% centerText(handles.uicontrols.text.text_sensitivity);
% centerText(handles.uicontrols.text.text_manualThreshold);
% centerText(handles.uicontrols.text.text_workflow_segmentation_objectDeclumping_cubeSideLengthDescr);
% centerText(handles.uicontrols.text.text_workflow_segmentation_objectDeclumping_cubeSideLengthUnit);
% centerText(handles.uicontrols.text.text_workflow_segmentation_objectDeclumping_watershed_distDescr);
% centerText(handles.uicontrols.text.text_workflow_segmentation_objectDeclumping_watershed_from);
% centerText(handles.uicontrols.text.text_workflow_segmentation_objectDeclumping_watershed_to);
% centerText(handles.uicontrols.text.text_removeVoxelsOfSize);
% centerText(handles.uicontrols.text.text_workflow_segmentation_postprocessing_stopProcessingN);
% centerText(handles.uicontrols.text.text_workflow_segmentation_postprocessing_removeBottomDescr);
% centerText(handles.uicontrols.text.text_workflow_segmentation_postprocessing_removeBottomUnit);
% centerText(handles.uicontrols.text.text_workflow_segmentation_postprocessing_mergeChDescr2);

%centerText(handles.uicontrols.text.text_parameters_filtering_filterRange);
%centerText(handles.uicontrols.text.text_parameters_mergingSplitting_mergingDescr1);
%centerText(handles.uicontrols.text.text_parameters_mergingSplitting_mergingDescr2);
%centerText(handles.uicontrols.text.text_parameters_mergingSplitting_splittingDescr1);
%centerText(handles.uicontrols.text.text_parameters_mergingSplitting_splittingDescr2);
%centerText(handles.uicontrols.text.text_parameters_mergingSplitting_splittingDescr3);
%centerText(handles.uicontrols.text.text_parameters_mergingSplitting_splittingDescr4);
%centerText(handles.uicontrols.text.text_parameters_mergingSplitting_splittingDescr1);
%centerText(handles.uicontrols.text.text_parameters_mergingSplitting_splittingDescr2);
%centerText(handles.uicontrols.text.text_intensity_summary);
%centerText(handles.uicontrols.text.text_parameters_intensityFeatures_range);
%centerText(handles.uicontrols.text.text_parameters_tagCells_rules);
%centerText(handles.uicontrols.text.text_parameters_tagCells_tagname);
%centerText(handles.uicontrols.text.text_parameters_tagCells_newRule);
%centerText(handles.uicontrols.text.text_intensity_summary);

% centerText(handles.uicontrols.text.text_workflow_cellTracking_searchRadius);
% centerText(handles.uicontrols.text.text_workflow_cellTracking_searchRadiusUnit);
% centerText(handles.uicontrols.text.text_workflow_cellTracking_dilateUnit);
% centerText(handles.handles_analysis.uicontrols.text.text_or);
% centerText(handles.handles_analysis.uicontrols.text.text_NCellsLoad);
