root = fileparts(mfilename('fullpath'));

fid = fopen(fullfile(root, '..', 'includes', 'biofilmQ_version.txt'));
versions = textscan(fid, '%s');
fclose(fid);

version_long_without_v = versions{1}{1};
version_long_without_v(1) = [];

% create mex files
rel_paths = {...
%     'export/visualization/paraview/mtVTK library/miniz.c', ...
    'export/visualization/paraview/mtVTK library/zstream.c', ...
    'performance/checkVarsMatFile/checkVarnames.c', ...
    };

for i = 1:numel(rel_paths)
    rel_path = rel_paths{i};
    full_path = fullfile(root, '..', 'includes', rel_path);
    
    disp(full_path)
    
    mex(full_path, '-outdir', fileparts(full_path));
end

% BiofilmQ with MCR installer with deploytool
deploytool('-package', 'deployment\BiofilmQ_incl_mcr.prj');
deploytool('-package', 'deployment\BiofilmQ.prj');

% BiofilmQ exe with mcc
% mcc(...
%     '-o', 'BiofilmQ', ...
%     '-W', strcat('main:BiofilmQ,version=', version_long_without_v), ...
%     '-T', 'link:exe', ...
%     '-d', fullfile(root, 'files-for-deployment', 'BiofilmQ'), ...
%     '-v', ...
%     fullfile(root, '..', 'BiofilmQ.m'), ...
%     '-a', fullfile(root, '..', 'includes'), ...
%     '-r', fullfile(root, 'BiofilmQ_incl_mcr_resources', 'icon.ico') ...
%     );