function handles = enable_single_cell_properties(handles)

% Update parameter table

cellParametersCalculate =...
    {
    % Filter parameters
    'Filter objects', false	, 'Click to see options', [], [], 'None', [],...
    'Use the filter option to flag objects, which shall be excluded from the data (for instance background objects). After filtering, objects not within the indicated range are excluded from further analysis, but only deleted, if you perform the task <i>"Remove objects which did not pass filtering"</i>. To perform this second step is highly recommended to reduce file sizes. Only those parameters are available for filtering which have been calculated, yet. To extend the list of available filtering parameters, execute "Calculate object parameters" twice.', ...
    'usage/parameter_calculation.html#filter-objects';...
    
    'Remove objects which did not pass filtering', false, '', [], [], 'None', [],...
    'Delete objects from the dataset, which have been flagged by the filtering module <i>"Filter objects"</i>.', ...
    'usage/parameter_calculation.html#remove-objects-which-did-not-pass-filtering';...
    
    'Remove objects on the image border', false, '', [], [], 'None', [],...
    'Remove objects which are intersecting with the crop rectangle (in case the image was cropped) or the image border.', ...
    'usage/parameter_calculation.html#remove-objects-on-the-image-border';...
    
    'Remove object parameters, option: parameters', false, '', 'char', 'Please enter the parameters (separated by comma) which shall no longer be associated with each object.', 'None', [],...
    'Remove unused/unwanted parameters from the dataset for instance to decrease the file size.', ...
    'usage/parameter_calculation.html#remove-object-parameters';...
    
    % Intelliganet merging
    % 'Intelligent merging/splitting of single cells (deprecated)', false, 'Click to see options', [], [], 'Cells are modified, all already calculated parameters are lost!', 'Size, aspect ratio and orientation by ellipsoidal fit',...
    % 'Automatically curate single cell data by appropriate merging and splitting of under and over-segmented cells using clustering approaches (recommended to perform). This task can only be performed only once.', ...
    % 'usage/parameter_calculation.html';...
    
    % Object parameters
    'Surface properties, option: range [vox]', false, 30, 'numeric', 'Enter a range value [in vox].',  'Surface_LocalRoughness, Surface_PerSubstrateArea, Surface_LocalThickness, Biofilm_MeanThickness (global), Biofilm_Roughness (global), Biofilm_OuterSurface (global)', [],...
    'Supported ONLY for cube segmentation. Calculate surface properties per cube object. For the local roughness the amount of surfac earea around the centroid in a specified range is calculated (local roughness in terms of surface per volume). In addition cubes with identical x and y center positions are merged into a pillar. For each pillar the surface area per pillar base area and the local thickness in terms of local height [in um] is calculated.', ...
    'usage/parameter_calculation.html#surface-properties';...
    
    'Substrate area', false, '', 'numeric', 'Please enter the index at which the substrate is located in your tif stack.','Architecture_LocalSubstrateArea, Biofilm_SubstrateArea', [],...
    'Calculate area at which the biofilm is attached to the substrate. The substrate is assumed to be the brightest layer of cells in the field of view. If you wish to specify a different substrate index, please insert it in the text field.', ...
    'usage/parameter_calculation.html#substrate-area';...
    
    'Global biofilm properties', false, '', [], [], 'Biofilm_AspectRatio_HeightToLength Biofilm_AspectRatio_HeightToWidth, Biofilm_AspectRatio_LengthToWidth, Biofilm_BaseEccentricity, Biofilm_BaseArea [in um^2], Biofilm_Volume [in um^3]', [],...
    'Calculate global biofilm properties: aspect ratios, base area, base eccentricity (based on ellipsoidal fit) and total biofilm volume.', ...
    'usage/parameter_calculation.html#global-biofilm-properties';...
    
    'Convexity', false, '', [], [], 'Shape_Convexity', [],...
    'Calculate the convexity of each object. The convexity can be slightly above one for convex objects due to interpolation.', ...
    'usage/parameter_calculation.html';...
    
    'Distance to center biofilm', false, '', [], [], 'Distance_ToBiofilmCenter [in um], Distance_ToBiofilmCenterAtSubstrate [in um] </b>(distance to the center at the bottom of the biofilm)', [],...
    'Calculate the distance to the center of the biofilm and the distance to the center of the biofilm at the substrate (which is the center projected to the bottom of the biofilm).', ...
    'usage/parameter_calculation.html#distance-to-center-of-biofilm';...
    
    'Distance to surface, option: resolution [vox]', false, 20, 'numeric', 'Enter the smoothing range [in vox] to estimate the global biofilm shape.', 'distanceToSurface [in um]', [],...
    'Estimate the distance to the <i>upper</i> biofilm outer surface for each object.', ...
    'usage/parameter_calculation.html#distance-to-surface';....
    
    'Distance to specific object, option: object ID', false, '', 'numeric', 'Enter the ID of the specific object the centroid-to-centroid distance shall be measured to.', 'distanceToCell_(ID) [in um]', [],...
    'Calculate the distance to a specific object.', ...
    'usage/parameter_calculation.html#distance-to-specific-object';...
    
    'Local density, option: range [vox]', false, 30, 'numeric', 'Enter the range for the calculation of the local density [in vox].', 'Architecture_LocalNumberDensity_(range), Architecture_LocalDensity_(range)', [],...
    'Calculate the local number density (number of cells/sphere of indicated diameter, applicable mainly for sinlge-cell segmentation) and the local density (occupied volume fraction, applicable for all types of segmentation). Please note that the local number density is not corrected for image edge effects, whereas the local density is corrected.', ...
    'usage/parameter_calculation.html#local-density';...
    
    % Single cell properties
    
    'Size, aspect ratio and orientation by ellipsoidal fit', false, '', [], [], 'Orientation_Matrix </b>(3x3 matrix containing eigenvectors of each object) and <b>Shape_Length, Shape_Height and Shape_Width [in um], Shape_AspectRatio_LengthToWidth, Shape_AspectRatio_HeightToWidth', [],...
    'Recommended ONLY for single-cell segmentation. Fit an ellipse into each object to calculate eigenvectors and object dimensions. Then calculate the aspect ratio (longest axis/smallest axis and intermediate axis/smallest axis) of each object.', ...
    'usage/parameter_calculation.html';...
    
    'Distance to nearest neighbor, option: channel', false, 1, 'numeric', 'Please enter the channel number containing the objects you want to measure the closest distance to. Note the the image has to be segmented.', 'Distance_ToNearestNeighbor [in um]', [],...
    'Calculate the centroid-to-centroid distance to the nearest neighbor in a specific channel.', ...
    'usage/parameter_calculation.html#distance-to-nearest-neighbor';...
    
    'Inter cell spacing, option: screening range [vox]', false, 20, 'numeric', 'Please enter a screening range [in vox].', 'Distance_InterCellSpacing_Mean, Distance_InterCellSpacing_Min [both in um] </b>(average and minimal inter-cell-spacing per cell), <b>Distance_InterCellSpacing_Variance [in um]</b> (variance of the inter-cell-spacing per cell)', [],...
    'Recommended ONLY for single-cell segmentation. Quantify the wall-to-wall distance for each object. Random points are selected on the surface of each object and the perpendicular distances to the next surfaces are calculated.', ...
    'usage/parameter_calculation.html#inter-cell-spacing';....
        
    'Alignments and nematic order parameter, option: range [vox]', false, 30, 'numeric', 'Enter the range for the calculation of the nematic order parameter [in vox]', 'Alignment_Zaxis, Alignment_Radial, Alignment_Flow [in rad], Architecture_NematicOrderParameter_(range)', 'Size, aspect ratio and orientation by ellipsoidal fit',...
    'Recommended ONLY for single-cell segmentation. Calculate the vertical alignment, the alignment with the radial vector pointing to the center of the biofilm and the alignment with the direction of the external flow as well as the local nematic order around each cell.', ...
    'usage/parameter_calculation.html#nematic-order-parameter';...
    
    % Intensity properties
    'Fluorescence properties', false, 'Click to see options', [], [], 'This module can measure a vast amount of different parameters (see below)', [],...
    'Calculate fluorescence properties, perform correlations between different fluorescence channels and extract information about fluorescence foci.', ...
    'usage/parameter_calculation.html#fluorescence-properties';...
    
    % Tag cells
    'Tag cells', false, 'Click to see options', [], [], 'Name of tagged cells can be freely choosen', [],...
    'Tag cells following certain criteria with user-defined tag names.', ...
    'usage/parameter_calculation.html#id7';...
    
    % Connect cells for 3D printing
    'Connect cells for 3D-printing', false, '', [], [], 'None', [],...
    'Connect all free-hanging objects with thin bridges to obtain one single object for 3D-printing. <font color="red">WARNING: This module will delete all previously measured properties!', ...
    'usage/parameter_calculation.html';...
    
    % Custom parameter
    'Custom parameter', false, 'Click to see options', [], [], 'Name of new Parameter can be freely choosen', [],...
    'Calculate custom parameter from a combination of already calculated parameters.', ...
    'usage/parameter_calculation.html#id7';...
    
    % User-defined property
    'Parameter based on user-defined Matlab script', false, '', 'file', 'Please choose a Matlab script.', 'User_defined', [],...
    'Use the script "includes/cell processing/actions/user-defined parameters/template.m" as template for creating further models', ...
    'usage/parameter_calculation.html#custom-parameters'};

handles.uitables.cellParametersCalculate.Data = cellParametersCalculate(:, 1:3);
handles.tableData = cellParametersCalculate;

% Enable foci measurements
handles.uicontrols.popupmenu.intensity_task.String{end+1} = 'Number of fluorescence foci';
handles.uicontrols.popupmenu.segmentationMethod.String = {'Thresholding', 'Label image'};

objectHeight = handles.settings.objectHeight;

handles.layout.boxes.segmentationMethod.Heights = [objectHeight, -1, objectHeight, -1];
handles.layout.boxes.segmentation.Heights = [170, -1];

% modify menu bar
handles.menuHandles.menues.menu_process_all_select_cellParams.Text = ...
    'Calculate cell parameters';


