
%
% This program is free software: you can redistribute it and/or modify
% it under the terms of the GNU General Public License as published by
% the Free Software Foundation, either version 3 of the License, or
% (at your option) any later version.
%
% This program is distributed in the hope that it will be useful,
% but WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
% GNU General Public License for more details.
%
% You should have received a copy of the GNU General Public License
% along with this program.  If not, see <http://www.gnu.org/licenses/>.
%
%%

function about

versions = textscan(fopen('biofilmQ_version.txt'), '%s');
version = versions{1}{1}; % long

msgbox({sprintf('BiofilmQ %s', version),...
    '',...
    'Copyright (c) 2016-2019 Raimo Hartmann (raimo.hartmann@gmail.com).',...
    'Copyright (c) 2018-2023 Hannah Jeckel (jeckel.hannah@gmail.com).',...
    'Copyright (c) 2018-2021 Eric Jelli (eric.jelli@mpi-marburg.mpg.de).',...
    'Copyright (c) 2022-2023 Niklas Netter (niklas.netter@unibas.ch).',...
    'Copyright (c) 2020-2023 Eva Jiménez-Siebert (eva.j.siebert@unibas.ch).',...
    'Copyright (c) 2016-2023 Drescher-lab, Biozentrum Basel, Basel, Switzerland', ...
    '',...
    'BiofilmQ was developed by Raimo Hartmann, Hannah Jeckel and Eric Jelli and extended by Niklas Netter and Eva Jiménez-Siebert.',...
    '',...
    'This program is free software: you can redistribute it and/or modify',...
    'it under the terms of the GNU General Public License as published by',...
    'the Free Software Foundation, either version 3 of the License, or',...
    '(at your option) any later version.',...
    '',...
    'This program is distributed in the hope that it will be useful,',...
    'but WITHOUT ANY WARRANTY; without even the implied warranty of',...
    'MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the',...
    'GNU General Public License for more details.',...
    '',...
    'You should have received a copy of the GNU General Public License',...
    'along with this program.  If not, see https://www.gnu.org/licenses/.'}, 'About', 'help', 'modal');