%%
% BacStalk
%
% Copyright (c) 2018 Raimo Hartmann & Muriel van Teeseling <bacstalk@gmail.com>
% Copyright (c) 2018 Drescher-lab, Max Planck Institute for Terrestrial Microbiology, Marburg, Germany
% Copyright (c) 2018 Thanbichler-lab, Philipps Universitaet, Marburg, Germany
%
% This program is free software: you can redistribute it and/or modify
% it under the terms of the GNU General Public License as published by
% the Free Software Foundation, either version 3 of the License, or
% (at your option) any later version.
%
% This program is distributed in the hope that it will be useful,
% but WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
% GNU General Public License for more details.
%
% You should have received a copy of the GNU General Public License
% along with this program.  If not, see <http://www.gnu.org/licenses/>.
%
%%

function about

versions = textscan(fopen('biofilmQ_version.txt'), '%s');
version = versions{1}{1}; % long

msgbox({sprintf('BiofilmQ %s', version),...
    '',...
    'Copyright (c) 2019 Raimo Hartmann (raimo.hartmann@gmail.com).',...
    'Copyright (c) 2020 Hannah Jeckel (hannah.jeckel@mpi-marburg.mpg.de).',...
    'Copyright (c) 2020 Eric Jelli (eric.jelli@mpi-marburg.mpg.de).',...
    'Copyright (c) 2020 Drescher-lab, Max Planck Institute for Terrestrial Microbiology, Marburg, Germany', ...
    '',...
    'BiofilmQ was developed by Raimo Hartmann, Hannah Jeckel and Eric Jelli.',...
    '',...
    'This program is free software: you can redistribute it and/or modify',...
    'it under the terms of the GNU General Public License as published by',...
    'the Free Software Foundation, either version 3 of the License, or',...
    '(at your option) any later version.',...
    '',...
    'This program is distributed in the hope that it will be useful,',...
    'but WITHOUT ANY WARRANTY; without even the implied warranty of',...
    'MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the',...
    'GNU General Public License for more details.',...
    '',...
    'You should have received a copy of the GNU General Public License',...
    'along with this program.  If not, see https://www.gnu.org/licenses/.'}, 'About', 'help', 'modal');