function handles = enable_cell_tracking(handles)
handles.layout.tabs.workflow_cellTracking.Children.Children.Children.Title  = 'Cell tracking';
handles.uicontrols.pushbutton.pushbutton_action_trackCells.String = 'Track cells';
handles.uicontrols.text.text_workflow_cellTracking_descr.String = ...
        {'Tracking of cells based on the volumetric overlap of two cells in consecutive frames.'; ...
        ''; ...                                                                               }
    '   Calculated cell parameters:'; ...
    '     - Track_Parent'; ...
    '     - Track_Grandparent'; ...
    '     - Track_ID'; ...
    '     - Track_GrowthRate [in cubic um per min]'};
handles.uicontrols.popupmenu.trackMethod.String = ...
    {'Different trackIDs for all cells in the first frame'; ...
    'Same trackID for all cells in the first frame'      };

handles.uicontrols.checkbox.trackCellsDilate.String = ...
    'Dilate cells before calculating overlap for';


% modify menu bar
handles.menuHandles.menues.menu_process_all_select_trackCells.Text = ...
    'Track cells';