function handles = watershed_box_panel(handles, debug)


if nargin < 2
    debug = false;
end
        if debug
            padding = 8;
            spacing = 8;
            objectHeight = 22;
  
            f = figure();
            
        else
            padding = handles.settings.padding;
            spacing = handles.settings.spacing;
            objectHeight = handles.settings.objectHeight;
            f = handles.mainFig;
        end
        
        %% Interface definitions

        handles.layout.uipanels.panel_declumpingOptions = uix.Panel( ...
        'Parent', f, ...
        'Padding', padding, ...
        'Tag', 'uipanel_declumpingOptions', ...
        'Title', 'Watershedding options'); 
    
        % Labels
        handles.uicontrols.text.text_workflow_segmentation_objectDeclumping_distDescr = ...
        uicontrol( ...
            'Tag', 'text_workflow_segmentation_objectDeclumping_distDescr', ...
            'Style', 'text', ...
            'HorizontalAlignment', 'left', ...
            'String', 'Distance to cell border', ...
            'TooltipString', 'Use for objects without distinct indensity maxima (e.g. strongly overexposed images)');
        
        handles.uicontrols.text.text_workflow_segmentation_objectDeclumping_cutIndentions_from = ...
        uicontrol( ...
            'Tag', 'text_workflow_segmentation_objectDeclumping_cutIndentions_from', ...
            'Style', 'text', ...
            'HorizontalAlignment', 'right', ...
            'FontAngle', 'italic', ...
            'String', 'no influce');
        
        handles.uicontrols.text.text_workflow_segmentation_objectDeclumping_cutIndentions_to = ...
        uicontrol( ...
            'Tag', 'text_workflow_segmentation_objectDeclumping_cutIndentions_to', ...
            'Style', 'text', ...
            'HorizontalAlignment', 'left', ...
            'FontAngle', 'italic', ...
            'String', 'strong influce');

        handles.uicontrols.text.text_workflow_segmentation_objectDeclumping_tempCorrDescr = ...
        uicontrol( ...
            'Tag', 'text_workflow_segmentation_objectDeclumping_tempCorrDescr', ...
            'Style', 'text', ...
            'HorizontalAlignment', 'left', ...
            'FontAngle', 'italic', ...
            'String', 'Tries to reduce oversegmentation by comparing the segmentation result with the result of the previous frame.');
        
        %checkboxes
        handles.uicontrols.checkbox.skipDeclumpingFirstFrame = ...
        uicontrol( ...
            'Tag', 'skipDeclumpingFirstFrame', ...
            'Style', 'checkbox', ...
            'HorizontalAlignment', 'center', ...
            'String', 'No watershedding for first frame');
        
        handles.uicontrols.checkbox.temporalCorrection = ...
        uicontrol( ...
            'Tag', 'temporalCorrection', ...
            'Style', 'checkbox', ...
            'HorizontalAlignment', 'center', ...
            'String', 'Temporal correlation (if possible)');
        
        % edits
        handles.uicontrols.edit.cutIndentions = ...
        uicontrol( ...
            'Tag', 'cutIndentions', ...
            'Style', 'edit', ...
            'String', '0');
        
        % slider
        handles.uicontrols.slider.slider_cutIndentions = ...
        uicontrol( ...
            'Tag', 'slider_cutIndentions', ...
            'Style', 'slider', ...
            'Min', 0.0, ...
            'Max', 1.0);
            
        
        
        
        %% Interface Layout

        h = uix.VBox( ...
            'Parent', handles.layout.uipanels.panel_declumpingOptions, ...
            'Padding', 4*padding, ...
            'Spacing', spacing);
        
            h3 = uix.VBox( ...
                'Parent', h, ...
                'Padding', 0, ...
                'Spacing', spacing);

                h3_1 = uix.HBox('Parent', h3, ...
                    'Padding', 0, ...
                    'Spacing', spacing);

                    handles.uicontrols.text.text_workflow_segmentation_objectDeclumping_distDescr.Parent = h3_1;
                    handles.uicontrols.text.text_workflow_segmentation_objectDeclumping_cutIndentions_from.Parent = h3_1;
                    handles.uicontrols.slider.slider_cutIndentions.Parent = h3_1;
                    handles.uicontrols.text.text_workflow_segmentation_objectDeclumping_cutIndentions_to.Parent = h3_1;
                    handles.uicontrols.edit.cutIndentions.Parent = h3_1;

                h3_1.Widths = [120, 50, 100, 70, 30];

                handles.uicontrols.checkbox.skipDeclumpingFirstFrame.Parent = h3;

                handles.uicontrols.checkbox.temporalCorrection.Parent = h3;

                h3_2 = uix.HBox('Parent', h3, 'Padding', 0, 'Spacing', spacing);
                    uix.Empty('Parent', h3_2);
                    handles.uicontrols.text.text_workflow_segmentation_objectDeclumping_tempCorrDescr.Parent = h3_2;
                h3_2.Widths = [20, -1];

            h3.Heights = objectHeight*[1 1 1 2];
       
        
    %% Callbacks
    if ~debug     
        handles.uicontrols.checkbox.skipDeclumpingFirstFrame.Callback = ...
            @(hObject,eventdata)additionalCallbacks('skipDeclumpingFirstFrame_Callback',hObject,eventdata,guidata(hObject));
        
        handles.uicontrols.checkbox.temporalCorrection.Callback = ...
            @(hObject,eventdata)BiofilmQ('temporalCorrection_Callback',hObject,eventdata,guidata(hObject));
        
        handles.uicontrols.edit.cutIndentions.Callback = ...
            @(hObject,eventdata)BiofilmQ('cutIndentions_Callback',hObject,eventdata,guidata(hObject));
        
        handles.uicontrols.slider.slider_cutIndentions.Callback = ...
            @(hObject,eventdata)BiofilmQ('slider_cutIndentions_Callback',hObject,eventdata,guidata(hObject));
        
        
    end


end

